name: Keep Old Bee Bot Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Manual trigger if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Old bee Bot server
        run: |
          curl https://ol-bee-bot.onrender.com/