name: Keep Old Bee Bot Awake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *" # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Old Bee Bot server
        run: |
          curl https://ol-bee-bot.onrender.com/
